name: Build and Deploy React Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the current repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      # Set up Node.js for building the React app
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          corepack enable
          yarn install
          yarn run build

      # Checkout the target repository to push the build
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: Z-Editor/z-editor.github.io
          token: ${{ secrets.Z_ACCESS_TOKEN }} # Use a personal access token with repo permissions
          ref: main # Target branch
          path: target-repo

      # Copy the build output to the target repo directory
      - name: Copy build output
        run: |
          # rm -rf target-repo/*
          cp -r dist/* target-repo/

      # Commit and push changes to the target repository
      - name: Commit and push changes
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy React app from the master branch"
          git push origin main
